name: merval_argentina_dbt
version: 1.0.0
config-version: 2

profile: merval_argentina_profile

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages

vars:
  portfolio_id: argentina_demo_portfolio
  w_ggal: 0.25
  w_ypfd: 0.25
  w_pamp: 0.20
  w_bma: 0.15
  w_cepu: 0.15

models:
  merval_argentina_dbt:
    +materialized: view
    +persist_docs:
      relation: true
      columns: true
    staging:
      +schema: dbt_processed_market
    intermediate:
      +schema: dbt_processed_market
      +materialized: table
    marts:
      +schema: serving_market
      +materialized: table
      +tags: ["serving"]
