-- Input: int_basket_horizon_analytics
-- Grain: one row per basket_horizon_id
-- Purpose: publish the final basket-horizon metrics mart that combines notebook metrics with dbt validation fields.
-- Layer: serving

select
    basket_horizon_id,
    basket_name,
    basket_label,
    horizon_name,
    horizon_label,
    weighting_method,
    macro_rationale,
    horizon_description,
    investor_profile_anchor,
    lookback_days,
    evaluation_days,
    simulation_days,
    max_weight,
    min_weight,
    expected_portfolio_return,
    portfolio_volatility,
    weighted_sharpe,
    sortino_ratio,
    calmar_ratio,
    max_drawdown,
    realized_cumulative_return,
    downside_deviation,
    concentration_risk_hhi,
    effective_number_of_assets,
    diversification_ratio,
    diversification_effect,
    average_pairwise_correlation,
    weighted_beta_merval,
    weighted_beta_eem,
    weighted_corr_merval,
    weighted_corr_fx,
    num_assets,
    risk_profile,
    risk_profile_reason,
    macro_risk_note,
    dbt_num_assets,
    dbt_weight_concentration_hhi,
    dbt_effective_number_of_assets,
    dbt_average_pairwise_correlation,
    dbt_portfolio_volatility_from_covariance,
    dbt_diversification_ratio,
    dbt_diversification_effect,
    dbt_weighted_beta_merval,
    dbt_weighted_beta_eem,
    dbt_weighted_corr_fx,
    dbt_weighted_corr_merval,
    concentration_gap,
    beta_merval_gap,
    beta_eem_gap,
    diversification_effect_gap,
    ingestion_timestamp,
    run_id
from {{ ref('int_basket_horizon_analytics') }}
