-- Input: int_basket_horizon_weights and mart_basket_horizon_method_comparison
-- Grain: one row per basket_horizon_id and ticker
-- Purpose: publish the final weight table with basket, horizon, stock-level context, and winning-strategy flags in one place.
-- Layer: serving

with weights as (
    select
        basket_horizon_id,
        basket_name,
        basket_label,
        horizon_name,
        horizon_label,
        weighting_method,
        ticker,
        basket_order,
        sector,
        macro_rationale,
        lookback_days,
        evaluation_days,
        simulation_days,
        max_weight,
        min_weight,
        investor_profile_anchor,
        weight,
        weight_rank,
        average_return,
        volatility,
        sharpe_ratio,
        sortino_ratio,
        calmar_ratio,
        downside_frequency,
        max_drawdown,
        corr_with_merval,
        corr_with_fx,
        stock_type,
        beta_vs_merval,
        beta_vs_eem,
        ingestion_timestamp,
        run_id
    from {{ ref('int_basket_horizon_weights') }}
),
strategy as (
    select
        basket_horizon_id,
        selection_score,
        selection_score_version,
        risk_adjusted_score,
        return_score,
        risk_control_score,
        tail_resilience_score,
        diversification_quality_score,
        method_rank_within_basket_horizon,
        basket_rank_within_horizon,
        is_best_method_for_basket_horizon,
        is_best_basket_for_horizon,
        horizon_winner_reason
    from {{ ref('mart_basket_horizon_method_comparison') }}
)
select
    w.basket_horizon_id,
    w.basket_name,
    w.basket_label,
    w.horizon_name,
    w.horizon_label,
    w.weighting_method,
    w.ticker,
    w.basket_order,
    w.sector,
    w.macro_rationale,
    w.lookback_days,
    w.evaluation_days,
    w.simulation_days,
    w.max_weight,
    w.min_weight,
    w.investor_profile_anchor,
    w.weight,
    w.weight_rank,
    s.selection_score,
    s.selection_score_version,
    s.risk_adjusted_score,
    s.return_score,
    s.risk_control_score,
    s.tail_resilience_score,
    s.diversification_quality_score,
    s.method_rank_within_basket_horizon,
    s.basket_rank_within_horizon,
    s.is_best_method_for_basket_horizon,
    s.is_best_basket_for_horizon,
    s.horizon_winner_reason,
    w.average_return,
    w.volatility,
    w.sharpe_ratio,
    w.sortino_ratio,
    w.calmar_ratio,
    w.downside_frequency,
    w.max_drawdown,
    w.corr_with_merval,
    w.corr_with_fx,
    w.stock_type,
    w.beta_vs_merval,
    w.beta_vs_eem,
    w.ingestion_timestamp,
    w.run_id
from weights as w
left join strategy as s
    on w.basket_horizon_id = s.basket_horizon_id
